export const metadata = {
    title: 'My-next-js-app | Profile',
    description: 'Generated by My-next-js app',
  }
const ProfilePage = () => {
    return (
        <div>
            <h2>Profile page</h2>
        </div>
    );
};

export default ProfilePage;