export const metadata = {
    title: 'My-next-js-app | Dashboard | AddProduct',
    description: 'Generated by My-next-js app',
  }
const AddProductPage = () => {
    return (
        <div>
            <h2>Add product</h2>
        </div>
    );
};

export default AddProductPage;