export const metadata = {
    title: 'My-next-js-app | Dashboard | Manage Product',
    description: 'Generated by My-next-js app',
  }

const ManageProductPage = () => {
    return (
        <div>
           <h2> Manage Product Page</h2>
        </div>
    );
};

export default ManageProductPage;