export const metadata = {
    title: 'My-next-js-app | About',
    description: 'Generated by My-next-js app',
  }

const AboutPage = () => {
    return (
        <div>
            <h2>About page</h2>
        </div>
    );
};

export default AboutPage;