import Image from 'next/image'
export const metadata = {
  title: 'My-next-js-app | Home',
  description: 'Generated by My-next-js app',
}

 const HomePage=()=> {
  return (
    <main>
      <h2 className='text-5xl'>Home</h2>
    </main>
  )
}
export default HomePage;