import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My-next-js app',
  description: 'Generated by My-next-js app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <li className='list-none'>Home</li>
        </nav>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  )
}
