export const metadata = {
    title: 'My-next-js-app | Dashboard',
    description: 'Generated by My-next-js app',
  }
const DashboardPage = () => {
    return (
        <div>
            <h2>Dashboard page</h2>
        </div>
    );
};

export default DashboardPage;