import Link from "next/link";

export const metadata = {
    title: 'My-next-js-app | Blog',
    description: 'Generated by My-next-js app',
  }
  const blogs=[
    {
        id:1,
        year: 2023,
        title: 'title1'
    },
    {
        id:2,
        year: 2023,
        title: 'title2'
    },
    {
        id:3,
        year: 2023,
        title: 'title3'
    },
    {
        id:4,
        year: 2023,
        title: 'title4'
    },
  ]

const BlogPage = () => {
    return (
        <div className="container mx-auto">
            {
                blogs.map(({id,year,title})=><Link className="block border border-orange-500 p-2 my-2" href={{
                    pathname: `blog/${year}/${id}`,
                    query: {
                        title: title
                    }
                }} key={id}>{title}</Link>)
            }
        </div>
    );
};

export default BlogPage;